#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='ja_JP.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path manpath pythonpath
typeset -guT PYTHONPATH pythonpath
typeset -guT LD_LIBRARY_PATH ld_library_path
typeset -x PATH MANPATH PYTHONPATH LD_LIBRARY_PATH

if [[ $OSTYPE == darwin* ]]; then
    typeset -gUT DYLD_LIBRARY_PATH dyld_library_path
    typeset -x DYLD_LIBRARY_PATH
fi

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $HOME/bin
  $path
)

#
# ManPaths
#
manpath=(
    /usr/local/opt/coreutils/libexec/gnuman(N-/)
    $manpath
)

#
# PythonPath
#
pythonpath=(
    $HOME/local/lib/python(N-/)
    $pythonpath
)

#
# LD_LIBRARY_PATH
#
ld_library_path=(
    $HOME/local/lib(N-/)
    $ld_library_path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# GISTY
#
export GISTY_DIR="$HOME/work/gists"
export GISTY_ACCESS_TOKEN="840962b701e9c99c7ec3411bc693f53734d9727c"

#
# PostgreSQL
#
export PGDATA=/usr/local/var/postgres

#
# Docker
#
export DOCKER_HOST=tcp://localhost:2375

#
# Mono
#
export MONO_GAC_PREFIX=/usr/local

#
# Golang
#
if [ -x "`which go`" ]; then
    export GOROOT=`go env GOROOT`
    export GOPATH=$HOME/go
    path=( $GOROOT/bin(N-/) $GOPATH/bin(N-/) $path )
fi

#
# .NET Version Manager
#
export MONO_GAC_PREFIX=/usr/local
source dnvm.sh
export MONO_MANAGED_WATCHER=false

#
# Heroku
#
path=(
    /usr/local/heroku/bin(N-/)
    $path
)

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"

#
# Alias
#
alias ssh-vps01="ssh -p 10022 kimikato@vps01.29lab.jp"
alias ssh-vps02="ssh -p 10022 kimikato@vps02.29lab.jp"
alias sftp-vps01="sftp -P 10022 kimikato@vps01.29lab.jp"
alias sftp-vps01="sftp -P 10022 kimikato@vps02.29lab.jp"
